version: '3.7'
services:
    phpapp:
        image: tutum/apache-php
        container_name: hos_monitor_apache
        environment:
            - ALLOW_OVERRIDE=true
        ports:
            - "9000:80"
        volumes:
            - ./app:/app
    database:
        image: mariadb:10.3.9
        container_name: hos_monitor_mariadb
        volumes:
            - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
            - ./docker/mysql/data/:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=hosmonitor
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=dinsorsee
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: hos_monitor_phpmyadmin
        environment:
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=dinsorsee
            - PMA_HOST=database
        links:
            - database
        depends_on:
            - database
        ports:
            - 3031:80