version: '3.7'
services:
  database:
    image: mariadb:10.3.9
    container_name: hos_monitor_mariadb
    volumes:
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
      - ./docker/mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=hosmonitor
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dinsorsee
    expose:
      - '3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hos_monitor_phpmyadmin
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dinsorsee
      - PMA_HOST=database
    links:
      - database
    depends_on:
      - database
    ports:
      - '9001:80'
  nginx:
    build:
      context: ./docker/nginx
    container_name: hos_monitor_nginx
    restart: always
    volumes:
      - ./app:/var/app
    ports:
      - '9000:80'
  phpfpm:
    build:
      context: ./docker/php7-fpm
    container_name: hos_monitor_phpfpm
    restart: always
    volumes:
      - ./app:/var/app
    expose:
      - '9000'
